#!/bin/bash

# Will generate a modified .iso image of Ubuntu 14:04 LTS for use as a self contained training environments for use at Drupal Training Day evenets.
# Requirements:
# * 5-8 GB of storage.


dtd_remaster_prep() {
  # Create the remaster dir
  mkdir -p $dtd_build_dir/tmp/desktop/remaster
  # Copy the customization-scripts template
  cp -R $dtd_build_dir/lib/desktop/customization-scripts $dtd_build_dir/tmp/desktop/
  # Copy the dtd package into the scripts dir so it's copied into the chroot.
  cp $dtd_build_dir/var/build/tracks/dtd-tracks.tgz $dtd_build_dir/tmp/desktop/customization-scripts/
  # Copy stack and drush installer scripts.
  
  cp $dtd_build_dir/bin/dtd-stack $dtd_build_dir/tmp/desktop/customization-scripts/
  cp $dtd_build_dir/bin/dtd-drush $dtd_build_dir/tmp/desktop/customization-scripts/

}

dtd_build_desktop() {
  # Build the iso.
  dtd_remaster_prep desktop
  uck-remaster \
    $dtd_build_dir/var/sources/desktop/$dtd_src_desktop_file \
    $dtd_build_dir/tmp/desktop/customization-scripts \
    $dtd_build_dir/tmp/desktop/remaster
  mv $dtd_build_dir/tmp/desktop/remaster-new-files/livecd.iso $dtd_build_dir/var/build/desktop/$dtd_target_desktop_iso_file
}

