#!/bin/bash

# Generates a tailor made repository for the server iso

# Load config and sources.
dtd_load_config;
dtd_load_sources;
dtd_load_targets;

# Generate an iso image which will auto install all dtd components from the internet
# and create a repository for it.  
uck-unpack $DTD_BASE/var/sources $dtd_sources_server_file $DTD_BASE/tmp/server/

# uck-remaster-prepare-alternate remaster-iso-builder/
uck-remaster-pack-iso  ~/dtd-tools/tmp/server/remaster-builde

# Create a virtual machine.

# Create a disk

# Register the vm

# start the vm

# Check ssh connectivity.

# Check for complete file

# fetch compressed repository.


