#!/bin/bash

# Will build static packages of drush for offline installation

dtd_build_composer() {
  cp -v $dtd_build_dir/var/sources/composer/composer.phar $dtd_build_dir/var/build/composer/composer
}

dtd_build_drush() {
  cp -v $dtd_build_dir/var/sources/drush/drush.phar $dtd_build_dir/var/build/drush/drush
}
