#!/bin/bash

# Routines to build the usb disk
# from http://askubuntu.com/questions/249113/how-can-i-save-settings-when-booting-an-iso-file-from-hdd
# and https://help.ubuntu.com/community/Grub2/ISOBoot

# sudo sgdisk --zap-all /dev/sdb
# eject, insert... seriously?
# sudo sgdisk --new=1:0:0 --typecode=1:ef00 /dev/sdb
# sudo mkfs.vfat -F32 -n DTD2016 /dev/sdb1

dtd_build_disk_grub() {
  # Install grub
  sudo grub-install --force --removable --no-floppy --boot-directory=$dtd_cfg_disk_master_mount/boot $dtd_cfg_master/device
  cp $dtd_build_dir/lib/stick/grub.cfg $dtd_cfg_master_mount/boot/grub/
}

dtd_build_disk_desktop() {
  # Copy iso image
  cp $dtd_build_dir/var/build/desktop/$dtd_cfg_event_short-desktop.iso $dtd_cfg_master_mount/
  dd if=/dev/zero of=$dtd_cfg_master_mount/casper-rw bs=1M count=256
  mkfs.ext3 -F $dtd_cfg_master_mount/casper-rw
}

dtd_build_disk() {
  dtd_build_disk_grub
  dtd_build_disk_desktop
  dtd_build_disk_win
  dtd_build_disk_mac
  dtd_build_disk_lin
  dtd_build_disk_doc
  dtd_build_disk_extra

}
